import{ React} from 'react';

const Contract = ({instructor})=>{

  console.log("here",instructor)

const accepted=  async(e)=>{
  
const Status ="Accepted"
const percent =instructor.contract.percent
  const acc={Status,percent}
  e.preventDefault()
  const response = await fetch(`/api/instructors/updatecontract?authorid=${instructor._id}`, {
    method: 'PATCH',
    body: JSON.stringify(acc),
    headers: {
      'Content-Type': 'application/json'
    }
  })
  const json = await response.json()
  console.log("here")
  if (!response.ok) {
   console.log("error")
  }
  console.log("here")
  console.log(json)
  window.location.href=`/apps?userId=${instructor.userid}`


}


const rejected= async(e)=>{
 
  const Status ="Rejected"

  const percent =instructor.contract.percent
  const acc={Status,percent}
  e.preventDefault()
  const response = await fetch(`/api/instructors/updatecontract?authorid=${instructor._id}`, {
    method: 'PATCH',
    body: JSON.stringify(acc),
    headers: {
      'Content-Type': 'application/json'
    }
  })
  const json = await response.json()
  console.log("here")
  if (!response.ok) {
   console.log("error")
  }
  console.log("here")
  console.log(json)
  window.location.href=`/apps?userId=${instructor.userid}`

}

return(
    <div className ="contract">
        <h1> Course Contract Details </h1>
<body>
  <p>
    <p> This contract is to state that MR. has agreed to give our company Exclusive Rights to all his/her Courses, including But not limiited to, all videos created by him regarding the course content and other materials including :
     Exercises , Exams and  their solutions.</p>
    
     
      <p> Also that company is set to taken in {100-instructor.contract.percent}% of the Profit generated by the course , for each registartion to the 
     course by a user.  
</p>  

  </p>

  <p> Current Status : {instructor.contract.Status} </p>
</body>
<br></br>
{ (instructor.contract.Status=="Pending") && <div>
<button onClick={accepted}>Accept Contract</button>                     <button onClick={rejected}>Reject Contract</button>
</div>}
    </div>
)

}

export default Contract