import{ React} from 'react';

const Contract = ({courses})=>{
  console.log("here",courses)

const accepted=  async(e)=>{
const Status ="Accepted"
const percent =courses.contract.percent
  const acc={Status,percent}
  e.preventDefault()
  const response = await fetch(`/api/instructors/updatecontract?courseId=${courses._id}`, {
    method: 'PATCH',
    body: JSON.stringify(acc),
    headers: {
      'Content-Type': 'application/json'
    }
  })
  const json = await response.json()
  console.log("here")
  if (!response.ok) {
   console.log("error")
  }
  console.log("here")
  console.log(json)
  window.location.href=`/ViewContract?courseId=${courses._id}`
}


const rejected= async(e)=>{
  const Status ="Rejected"
  const percent =courses.contract.percent
    const acc={Status,percent}
  e.preventDefault()
  const response = await fetch(`/api/instructors/updatecontract?courseId=${courses._id}`, {
    method: 'PATCH',
    body: JSON.stringify(acc),
    headers: {
      'Content-Type': 'application/json'
    }
  })
  const json = await response.json()
  console.log("here")
  if (!response.ok) {
   console.log("error")
  }
  console.log("here")
  console.log(json)
  window.location.href=`/ViewContract?courseId=${courses._id}`

}

return(
    <div className ="contract">
        <h1> Course Contract Details </h1>
<body>
  <p>
    <p> This contract is to state that Mr. {courses._id}</p><p>,has agreed to give our company Exclusive Rights to his Course, {courses.title} ,including But not limiited to, all videos created by him regarding the course content and other materials including :
     Exercises , Exams and  their solutions.</p>
    
     
      <p> Also that company is set to taken in {courses.contract.percent}% of the Profit generated by the course , for each registartion to the 
     course by a user.  
</p>  

  </p>

  <p> Current Status : {courses.contract.Status}</p>
</body>
<br></br>
{ (courses.contract.Status=="Pending") && <div>
<button onClick={accepted}>Accept Contract</button>                     <button onClick={rejected}>Reject Contract</button>
</div>}
    </div>
)

}
export default Contract